# Generated by Django 5.0.4 on 2024-04-14 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id_prof', models.AutoField(primary_key=True, serialize=False)),
                ('nome_prof', models.CharField(max_length=100)),
                ('profissao_prof', models.CharField(max_length=100)),
                ('endereco_prof', models.CharField(max_length=200)),
                ('telefone_prof', models.CharField(max_length=20)),
                ('nomesocial_prof', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('data_consulta', models.DateTimeField()),
                ('profissional_consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.profissional')),
            ],
        ),
    ]
